dataset:
  name: seismo
  pair_id: 1  # Example: run on sub-datasets 1 to 3
model:
  name: Koopman
  observables: RadialBasisFunctions
  observables_cat_identity: false
  observables_float_param: 1.2146927808359949
  observables_include_state: true
  observables_int_param: 100
  observables_rbf_centers_number: 955
  regressor: EDMD
  regressor_dmd_rank: 85
  regressor_tlsq_rank: 6
  seed: 0
