dataset:
  name: seismo
  pair_id:
  - 7
model:
  name: Koopman
  observables: RandomFourierFeatures
  observables_cat_identity: false
  observables_float_param: 1.5557546164371079
  observables_include_state: true
  observables_int_param: 3
  observables_rbf_centers_number: 653
  regressor: EDMD
  regressor_dmd_rank: 28
  regressor_tlsq_rank: 14
  seed: 0
