dataset:
  name: ocean_das
  pair_id:
  - 9
model:
  name: Koopman
  observables: RandomFourierFeatures
  observables_cat_identity: true
  observables_float_param: 1.0528948061021193
  observables_include_state: false
  observables_int_param: 4
  observables_rbf_centers_number: 726
  regressor: DMD
  regressor_dmd_rank: 88
  regressor_tlsq_rank: 34
  seed: 0
